#        .__
# _____  |  |     STARSHIP SHELL PROMPT SETUP
# \__  \ |  |     Abdul Hakim (alarwasyi98)
#  / __ \|  |__   https://github.com/alarwasyi98/
# (____  /____/
#      \/

# Location:
# ~/.config/starship.toml

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Change the default prompt format
format = """\
[╭╴](238)$os$shell$username\
$all[╰─](238)$character"""

# Change the default prompt characters
[character]
error_symbol = "[](238)"
success_symbol = "[](238)"

[os]
format = '[$symbol](bold white) '
disabled = false

[os.symbols]
Windows = ''
Arch = '󰣇'
Ubuntu = ''
Macos = '󰀵'
EndeavourOS = ' '
Android = ''

# Shows the username
[username]
disabled = false            # disable in powershell
format = "[$user]($style) "
show_always = true
style_root = "black bold"
style_user = "green bold"

[shell]
format = ' with [$indicator]($style) | '
bash_indicator = ' bash'
zsh_indicator = '󰫫 zsh'
fish_indicator = ' fish'
pwsh_indicator = '󰨊 pwsh'
style = 'purple bold'
disabled = false

[directory]
format = "at [$path]($style)[$read_only]($read_only_style) "
home_symbol = "  ~"
read_only = "  "
read_only_style = "197"
truncation_length = 2
truncation_symbol = "…/"

[fill]
symbol = "_"

[git_branch]
format = "on [$symbol$branch]($style) "
style = "bold green"
symbol = " "
truncation_length = 5
truncation_symbol = "…/"

[git_status]
ahead = "⇡${count}"
behind = "⇣${count}"
conflicted = " "
deleted = " "
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
format = '[\($all_status$ahead_behind\)]($style) '
modified = " "
renamed = "󰑕 "
staged = '[  \($count\)](green)'
stashed = " "
style = "bold green"
untracked = " :$count"
up_to_date = " "

[docker_context]
format = "via [ $context](bold blue) "

[python]
python_binary = "python3"
symbol = "via [ $version]"

[nodejs]
disabled = false
format = "with [󰋘 $version](bold green) "

[bun]
disabled = false
format = "via [ $version]($style)"

[package]
format = "is [ $version]($style) "

[php]
format = "with [󰌟  $version](bold purple)"

[lua]
format = "with [󰢱 lua ](bold green)"

[kubernetes]
disabled = false
format = 'on [󱃾 $context\($namespace\)](bold purple) '

[kubernetes.context_aliases]
"clcreative-k8s-production" = "cl-k8s-prod"
"clcreative-k8s-staging" = "cl-k8s-staging"
